### ISSUE TITLE
Rename project to delve-relic-checklist

### ISSUE THREAD

**Issue by thisismydesign** [5k-mirrors/delve-relic-checklist#16]
To avoid future confusion and having to change links later.

We should decide whether we want to prefix projects with `poe-`. I'm kinda torn on this. If moved to 5k-mirrors this should obvious but might still help random visitors and ppl to e.g. search for it.

**Comment by Kexort** [comment]
The initial name of the repo was poe-relic-checklist because of the mentioned reasons, but I thought it was too long.

To help random visitors and ppl to e.g. search for it, we should add 'poe' topic to the repo.

I think we shouldn't put 'delve' into the name in case of we want to extend the checklist to legacy relics (for standard players).

**Comment by thisismydesign** [comment]
See your point about the length. I don't think topics are particularly helpful for visitors as they're rarely used in general. I don't usually pay attention to them. Anyways, no strong opinion there. However also with `poe-sniper` I think is makes sense to keep `poe`.

As far as Legacy (and other future) relics go I also thought about it and would actually make that as a separate project if any. I think the overlap in usage would be minimal and wouldn't warrant a shared service. Especially if new relics are introduced in a new league there would lots of uninteresting data loading on the screen. And there could be issues with having the same item twice (given e.g. that we keep identifying them by name, see #9).
